/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_test_Calck
#define DBUS_GLIB_CLIENT_WRAPPERS_org_test_Calck

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_test_Calck_add (DBusGProxy *proxy, const gint IN_first, const gint IN_second, gint* OUT_sum, GError **error)

{
  return dbus_g_proxy_call (proxy, "add", error, G_TYPE_INT, IN_first, G_TYPE_INT, IN_second, G_TYPE_INVALID, G_TYPE_INT, OUT_sum, G_TYPE_INVALID);
}

typedef void (*org_test_Calck_add_reply) (DBusGProxy *proxy, gint OUT_sum, GError *error, gpointer userdata);

static void
org_test_Calck_add_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_sum;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_sum, G_TYPE_INVALID);
  (*(org_test_Calck_add_reply)data->cb) (proxy, OUT_sum, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_test_Calck_add_async (DBusGProxy *proxy, const gint IN_first, const gint IN_second, org_test_Calck_add_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "add", org_test_Calck_add_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INT, IN_first, G_TYPE_INT, IN_second, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_test_Calck_sub (DBusGProxy *proxy, const gint IN_minuend, const gint IN_subtrahend, gint* OUT_difference, GError **error)

{
  return dbus_g_proxy_call (proxy, "sub", error, G_TYPE_INT, IN_minuend, G_TYPE_INT, IN_subtrahend, G_TYPE_INVALID, G_TYPE_INT, OUT_difference, G_TYPE_INVALID);
}

typedef void (*org_test_Calck_sub_reply) (DBusGProxy *proxy, gint OUT_difference, GError *error, gpointer userdata);

static void
org_test_Calck_sub_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_difference;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_difference, G_TYPE_INVALID);
  (*(org_test_Calck_sub_reply)data->cb) (proxy, OUT_difference, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_test_Calck_sub_async (DBusGProxy *proxy, const gint IN_minuend, const gint IN_subtrahend, org_test_Calck_sub_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "sub", org_test_Calck_sub_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INT, IN_minuend, G_TYPE_INT, IN_subtrahend, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_test_Calck */

G_END_DECLS
